### PR TITLE
Allow to load the notification view from a custom Nib

### PR DESCRIPTION
**Pull request by rivera-ernesto**
Some users may prefer to avoid confusion with the native notifications, or more likely, just be able to easily customize the notification view's appearance from a Nib file.

Next it would be cool to be able to customize presentation style for simpler fade-in/outs, etc.

### CODE REVIEW

**Comment by ekurutepe** [comment]
Hi Rivera,

I really like the idea. I haven't tested it but your implementation seems to be fine as well but I don't like having the nib filename as a parameter to the notify method. I'd envision this nib file won't change every time the user wants to show a notification. Wouldn't it be better to register this nib file with the `MPNotificationView` class such that when it's registered it will be used for every notification. Similar to how Apple handles header and footer views in the `UICollectionViewController`.

**Comment by rivera-ernesto** [comment]
Could be, but some applications may have severlar Nibs, like red ones with an alert icon, black ones with a bubble for incoming messages, etc.

**Comment by akurkin** [comment]
hey guys, I like this lib, but would like to apply more customization, and the approach proposed here is great.
For me it kinda makes sense to register a nib (or a few if you need to!) and then use default or specify a new one.

**Comment by ekurutepe** [comment]
This definitely a good feature. I'm merging this. Let's see if we can come up with a more elegant mechanism with registered nib names etc. in the future.

**Comment by ekurutepe** [comment]
@rivera-ernesto thanks a lot for your work.

**Comment by rivera-ernesto** [comment]
You're welcome!
Will work on that now, and also on customizing the animation part. Cheers

**Pull request merged**
